### ISSUE TITLE
Compile issue using the crate with ed25519-dalek

### ISSUE THREAD

**Issue by johnptoohey** [iqlusioninc/signatory#33]
Hi,
I'm trying to use ed25519-dalek et al for all my signature requirements for an Encrypted Data Vault (EDV) application. Stuck just trying to create a random keypair for my tests. Think I may have a wrong combination of crate versions, but am stuck on how to proceed from here. Any help would be very appreciated.

**Code**
```
      let keypair: Keypair;
      let mut csprng = OsRng;
      keypair = Keypair::generate(&mut csprng);
```
**Cargo.toml**
```
[dependencies]
base64 = "*"
ed25519 = "1.0.1"
signatory-dalek = "0.20.0"
ed25519-dalek = "1.0.0-pre.2"
rand = { version = "0.7", default-features = false, optional = true }
```

**Output** 
```
error[E0277]: the trait bound `rand_core::os::OsRng: rand_core::RngCore` is not satisfied
   --> zcaps-agent/src/lib.rs:97:37
    |
97  |         keypair = Keypair::generate(&mut csprng);
    |                                     ^^^^^^^^^^^ the trait `rand_core::RngCore` is not implemented for `rand_core::os::OsRng`
    |
   ::: /Users/johntoohey/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-dalek-1.0.0-pre.2/src/ed25519.rs:251:24
    |
251 |         R: CryptoRng + RngCore,
    |                        ------- required by this bound in `ed25519_dalek::ed25519::Keypair::generate`
    |
help: trait impl with same name found
   --> /Users/johntoohey/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.5.1/src/lib.rs:388:1
```

When I remove the dependency on signatory-dalek , I can compile without these errors. Is there a dependency issue here that I need to be aware of?

**Comment by tarcieri** [comment]
Continuing the discussion from https://github.com/dalek-cryptography/ed25519-dalek/issues/131

> Can I use a top-level crate that will include all its dependencies or do I always have to include stuff like rand, curveed25519 etc. I thought the signatory-dalek was that.

@johnptoohey I was just about to say `signatory-dalek` should do everything you need, but then I noticed it doesn't re-export `signatory` 😢

I will correct that in a newer version. However, for now you'll need `signatory` and `signatory-dalek`.

Once you have `signatory` in your Cargo.toml, you can import its Ed25519 private key type:

```rust
use signatory::ed25519::Seed;
```

To randomly generate a key with it, just call generate:

```rust
let ed25519_private_key = Seed::generate();
```

You can now instantiate a signer with it:

```rust
use signatory_dalek::Ed25519Signer;

let signer = Ed25519Signer::from(&seed);
```

**Comment by johnptoohey** [comment]
Thank you. This simplifies things and it works :-) One final question. Following the example from https://docs.rs/ed25519/1.0.1/ed25519/, and assuming I have created my Ed25519Signer as above. I create 
```
/// `HelloSigner` instantiated with an `ed25519-dalek` signature provider
pub type DalekHelloSigner = HelloSigner<Ed25519Signer>;
``` 
Can I now call ```DalekHelloSigner.sign(&person, &str)``` or do I need to further instantiate it?

**Comment by tarcieri** [comment]
You'd need to both instantiate it and define a method, however once instantiated, this should work:


```rust
let signer = Ed25519Signer::from(&ed25519_private_key);
let signature = signer.sign(&person);
```

**Comment by johnptoohey** [comment]
I have a valid Ed25519Signer but when I call signer.sign(...) I get 
```
[rustc E0599] [E] no method named `sign` found for struct `signatory_dalek::Ed25519Signer` in the current scope
method not found in `signatory_dalek::Ed25519Signer`
```
Full test code is 
```
    #[test]
    fn sign() {
        //pub type MySigner = Agent<Ed25519Signer>;

        let ed25519_private_key = ed25519::Seed::generate();
       
        let signer = Ed25519Signer::from(&ed25519_private_key);
        signer.sign("abcdef".as_ref());
    }
```

**Comment by tarcieri** [comment]
You'll need the `signatory::signature::Signature` trait in scope

**Comment by johnptoohey** [comment]
This code is from the comments in the crate, and it give errors. Using default branch for ```signatory/src/ed25519.rs```

Creating the Seed and Signer works, but I cannot use the Signer to sign or extract the public key.
 
```
    use signatory::ed25519;
    use signatory_dalek::{Ed25519Signer, Ed25519Verifier};

    #[test]
    fn sign() {
        //pub type MySigner = Agent<Ed25519Signer>;

        let ed25519_private_key = ed25519::Seed::generate();
        let signer = Ed25519Signer::from(&ed25519_private_key);
        let pk = ed25519::public_key(&signer).unwrap();
        assert_eq!(false, false);
    }
```

**Comment by tarcieri** [comment]
You still need:

```rust
use rust signatory::signature::Signature;
```

...and to get the public key, you'll additionally want:

```rust
use signatory::{PublicKeyed, signature::Signature};
```

**Comment by johnptoohey** [comment]
Finally :-) Thanks again for all your help.

```
use signatory::ed25519;
use signatory_dalek::{Ed25519Signer, Ed25519Verifier};

use signatory::{
    public_key::PublicKeyed, signature::Signature, signature::Signer, signature::Verifier,
};

```
```
    #[test]
    fn sign_verify() {
        let ed25519_private_key = ed25519::Seed::generate();

        let signer = Ed25519Signer::from(&ed25519_private_key);

        let msg = "How are you? Fine, thank you.";
        let sig = Signer::sign(&signer, msg.as_bytes());

        let pk = PublicKeyed::public_key(&signer).unwrap();
        let verifier = Ed25519Verifier::from(&pk);
        assert!(Verifier::verify(&verifier, msg.as_bytes(), &sig).is_ok());
    }
```

**Comment by tony-iqlusion** [comment]
Awesome! If you feel up to it, it'd be great if you can contribute the above as rustdoc documentation.

**Comment by tarcieri** [comment]
Awesome! If you feel up to it, it'd be great if you can contribute the above as rustdoc documentation.

**Comment by johnptoohey** [comment]
Not a problem. I'll create a MD doc that contains the code and how to use it. I'll send you a PR when I'm done.

**Comment by johnptoohey** [comment]
I have this MD file with two example tests. Does this work? @tarcieri 

## Sample Test case for Signing and Verifying a digital signature using the *signatory* crate 

The Signatory crates provides a unified API for accessing various crypto
providers for digital signatures. 

Signatory provides a thread-safe and object-safe API and implements providers
for many popular Rust crates, including [ed25519‑dalek], [*ring*], [secp256k1], 
and [sodiumoxide].

This example uses a unique private key generated by the ed25519 crate, signs a
piece of text using the Signer function from the signature crate, and then
verifies the signature using the corresponding public key.

The second test use a deterministic key generated from a user supplied *Secret*
and a *Salt*.

```rust
[dependencies]
base64 = "*"
signatory-dalek = "0.20.0"
signatory = "0.20.0"

sha2 = "0.9.0"
hmac = "0.8.0"
```

```rust
use signatory_dalek::{Ed25519Signer, Ed25519Verifier};

use signatory::{
    ed25519, public_key::PublicKeyed, signature::Signature, signature::Signer, signature::Verifier,
};

/// Generate a private key from a user supplied Secret and a Salt
fn key_from_seed_and_name(secret: &str, salt: &str) -> crypto_mac::Output<HmacSha256> {
    let to_hash = encode_config(format!("{}:{}", secret, salt), URL_SAFE);
    let mac = HmacSha256::new_varkey(&to_hash.into_bytes()).expect("HMAC can take key of any size");

    let result = mac.finalize();
    result
}
```
   
```rust
#[test]

fn sign_verify() {
     let ed25519_private_key = ed25519::Seed::generate();
     let signer = Ed25519Signer::from(&ed25519_private_key);
     let msg = "How are you?";
     let sig = Signer::sign(&signer, msg.as_bytes());

      let pk = PublicKeyed::public_key(&signer).unwrap();
      let verifier = Ed25519Verifier::from(&pk);
      assert!(Verifier::verify(&verifier, msg.as_bytes(), &sig).is_ok());
}

#[test]
    fn sign_verify_deterministic() {
        let key = key_from_seed_and_name("JT-1", "SALT");
        let bytes = key.into_bytes();
        let ed25519_private_key = ed25519::Seed::from_bytes(bytes).expect("Invalid key length");

        let signer = Ed25519Signer::from(&ed25519_private_key);
        let msg = "How are you? Fine, thank you.";
        let sig = Signer::sign(&signer, msg.as_bytes());

        let pk = PublicKeyed::public_key(&signer).unwrap();
        let verifier = Ed25519Verifier::from(&pk);
        assert!(Verifier::verify(&verifier, msg.as_bytes(), &sig).is_ok());
    }

```

**Comment by tarcieri** [comment]
@johnptoohey yep! mind opening a PR that adds it to the crate-level rustdoc?

**Comment by johnptoohey** [comment]
Have a new branch with the changes ready to go, but I need permission to create the branch on the main repo. Once I push my temp branch, I'll create the PR for you to approve.

**Comment by tarcieri** [comment]
Can you fork the repo and open a PR that way instead?

**Comment by johnptoohey** [comment]
Let me know if there is any low-hanging fruit I can take a run at, with any of these crypto projects.
