### ISSUE TITLE
Future of Signatory?

### ISSUE THREAD

**Issue by tony-iqlusion** [iqlusioninc/signatory#71]
Signatory began with the goal of creating a common API for producing and verifying digital signatures which worked across ECDSA, Ed25519. It was implemented as a set of wrappers for (mostly native code) backend provider crates which implemented those algorithms respectively.

We had an itch to scratch in creating it: [Tendermint KMS](https://github.com/iqlusioninc/tmkms), and the need to support multiple different signing backends through a common keyring API. While Signatory was created as a general-purpose digital signature library, as part of the KMS work we started taking on [Signatory provider crates which only make sense in the context of Tendermint KMS usage](https://github.com/iqlusioninc/signatory/tree/develop/signatory-ledger-tm).

In the time since, may of the most useful general purpose parts of Signatory have been extracted into other crates, most notably the RustCrypto [`signature`](https://docs.rs/signature), [`async-signature`](https://docs.rs/async-signature), [`ed25519`](https://docs.rs/ed25519) and [`ecdsa`](https://docs.rs/ecdsa).

Additionally three of the most notable provider crates: [`signatory-dalek`], [`signatory-ring`], and [`signatory-yubihsm`], are all now defunct:

- The upstream `ed25519-dalek` crate adopted the `signature::{Signer, Verifier}` traits and `ed25519::Signature` type, natively implementing what the wrapper crate previously provided
- The `signatory-ring` crate was obsoleted by [`ring-compat`](https://github.com/RustCrypto/ring-compat), which also wraps AEAD and digest functionality from *ring*
- The `yubihsm` crate similarly implemented the wrapper functionality natively, and now no longer depends on `signatory`.

This leaves the following providers:
- `signatory-ledger-tm` implements Tendermint KMS-specific Ed25519 signing support
- `signatory-secp256k1` is still useful as the upstream rust-bitcoin/rust-secp256k1 library provides the fastest and most mature Rust secp256k1 implementation, however with the [`k256` crate](https://docs.rs/k256/) now providing a semi-mature and semi-performant pure Rust implementation, at least at iqlusion we will probably cease using this crate
- `signatory-sodiumoxide` also provides an Ed25519 signature implementation which is still useful, however there is an [open PR to add native support for the `ed25519::Signature`](https://github.com/sodiumoxide/sodiumoxide/pull/434) type.

We have an open PR to add an SGX signing backend (#51), but this is another example of where the main interesting use case is Tendermint KMS. If such an SGX backend were optimized specifically for this use case, the enclave could act as a "smart signer" and help maintain various invariants about what it's signing as the Ledger app which `signatory-ledger-tm` wraps does today.

Question: is Signatory still valuable as a general purpose digital signature library? If it's been obsoleted in that capacity, and is now acting as an abstraction layer primarily for Tendermint KMS, should we move `signatory-ledger-tm` and the prospective SGX signing backend (#51) directly into the KMS repo instead?

**Comment by tomtau** [comment]
> If such an SGX backend were optimized specifically for this use case, the enclave could act as a "smart signer" and help maintain various invariants about what it's signing as the Ledger app which signatory-ledger-tm wraps does today.

Yes, that's what I meant by "push more TMKMS to SGX" in: https://github.com/iqlusioninc/tmkms/issues/53#issuecomment-641692437

IMHO this could be done progressively -- start off with the plain signatory/HSM-like signing, later add protobuf message parsing and basic validation of invariants... it could go to the "extreme" with the whole privval socket session / gRPC being managed inside SGX, but the tradeoff of trusted code size vs benefits of less indirection / having more validation/control inside the enclave should be carefully considered.

Having said that, even the "plain signatory" version can have more orthogonal features, independent of TMKMS, e.g. "enclave-to-remote enclave" backups.
@Cashmaney any comments?

> Question: is Signatory still valuable as a general purpose digital signature library? If it's been obsoleted in that capacity, and is now acting as an abstraction layer primarily for Tendermint KMS, should we move signatory-ledger-tm and the prospective SGX signing backend (#51) directly into the KMS repo instead?

Abstracting over HW-based signers could be useful to other projects beyond Tendermint, but if I understand it correctly, [ledger-validator-app](https://github.com/tendermint/ledger-validator-app) won't sign on arbitrary messages, so this abstraction is a bit of a lie and it's indeed only useful within TMKMS, so it perhaps makes sense to move it there.

**Comment by tony-iqlusion** [comment]
> if I understand it correctly, ledger-validator-app won't sign on arbitrary messages, so this abstraction is a bit of a lie and it's indeed only useful within TMKMS, so it perhaps makes sense to move it there.

I'm going to investigate what it looks like if I vendor it directly into Tendermint KMS. It seems like it would be much easier not to have a naive abstraction like Signatory for applications that are truly validator signing and not general purpose signing.

**Comment by tomtau** [comment]
@tony-iqlusion I tried to investigate the extreme version of "smart signer" enclave (running all of a patched tmkms softsign inside NE) in https://github.com/iqlusioninc/tmkms/pull/229

Some learnings from that:
- Unlike Ledger, (SGX or Nitro) enclaves don't have any persistent storage, so they need to:
1. get their configuration from outside (for now, there's "push-config" command one can execute on the host instance in NE)
2. get the key material from outside -- in SGX, the enclave is pushed the sealed key; in Nitro, the enclave is pushed the key sealed by AWS KMS, so it needs to send an attested decryption request to it.
3. store the state outside -- currently, it's just dumped to a file via a proxy process on the host instance... but one can perhaps do something else (use monotonic counters? write to S3 and have some policy config to restrict writing/reading to enclave attestation? ...)
- One can execute the full tendermint-rs parsing logic and validations and one can indirectly use the (untrusted) host networking -- with SGX, one can potentially do OCalls for required Unix/TCP socket handling (or have it abstracted out in EDP via "usercall extensions"); with Nitro, one can't do that directly, so needs to proxy via vsock (I guess one alternative option here would be to add vsock support in Tendermint privval)
- With SGX, one can do OCalls and log stuff directly to console, as with a normal application... with Nitro, one has access to console only in the debug mode -- I guess one can perhaps write a tracing impl that will output logs to vsock

Overall, yes, it seems all right to have this directly in tmkms, but if it's beyond a simple "keyring" and should be a "smart signer" that tries to reuse a lot of tmkms code, it'll need some changes in tmkms (not the ones in that draft PR -- that draft PR used workarounds by feature-guarding functionality related to the above items... it'll be better to introduce some abstractions for the above / perhaps separate out parts of tmkms in some crate? )

**Comment by tomtau** [comment]
> For SGX, it sounds like it can't do much beyond keywrapping the signing key.

One could possibly use monotonic counters and pin the sealed state against them: https://www.usenix.org/conference/usenixsecurity17/technical-sessions/presentation/matetic
But:
1. it requires Intel ME -- and server housing or cloud vendors generally disable that;
2. it has quite a few drawbacks (wear off; write latency and rate-limiting; potential counter resets/failing).

Some potential ideas (perhaps crazy / overkill 😂):
1. trusted third party -- roll out some custom auth layer over DB that will check the attestation doc in a request, similarly to what's done with services interfacing AWS NE;
2. Tendermint / Cosmos SDK-based network -- include tx-signer + light client and periodically broadcast a TX to self with a memo containing the latest (sealed?) state;
3. IPFS -- include IPFS client and push state to a IPNS location.

> Perhaps within the context of something like Nitro Enclaves the chain state could be persisted to e.g. DynamoDB, provided the enclave can be given some sort of service identity, and access to that database restricted to only that identity.

This identity / role restriction is documented for AWS KMS (in official docs + in Nitro Enclaves C SDK), but not sure if it works for other services -- it'd make sense, but perhaps it's not implemented (yet)

**Comment by tony-iqlusion** [comment]
I've decided to take Signatory in a different direction with #100

Please read the comments on that PR for more information and rationale.
